<?php

session_start();

require_once __DIR__ . '/otp/send_email_otp.php';
require_once __DIR__ . '/otp/send_phone_otp.php';

if (empty($_SESSION['csrf_token'])) {
    $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
}

$generalError = "";
$success = "";

if (empty($_SESSION['pending_verification'])) {
    header("Location: register.php");
    exit;
}

$pending = &$_SESSION['pending_verification'];

$userType = $pending['user_type'];
$email    = $pending['email'];
$phone    = $pending['phone'];


/*
|--------------------------------------------------------------------------
| Database
|--------------------------------------------------------------------------
*/

require_once __DIR__ . '/config/database.php';

$table = ($userType === 'doctor')
    ? 'doctors'
    : 'patients';

try {

    $conn = ($userType === 'doctor')
        ? Database::getConnection('doctors')
        : Database::getConnection('patients');

} catch (Exception $e) {

    $generalError =
        "Unable to connect. Please try again later.";
}


/*
|--------------------------------------------------------------------------
| Mask Email
|--------------------------------------------------------------------------
*/

function maskEmail(string $email): string
{
    [$name, $domain] = array_pad(
        explode("@", $email, 2),
        2,
        ""
    );

    if ($name === "") {
        return $email;
    }

    return substr($name, 0, 1)
        . str_repeat("*", max(1, strlen($name) - 1))
        . "@"
        . $domain;
}


/*
|--------------------------------------------------------------------------
| Mask Phone
|--------------------------------------------------------------------------
*/

function maskPhone(string $phone): string
{
    $digits = preg_replace('/\D+/', '', $phone);

    if (strlen($digits) <= 4) {
        return $phone;
    }

    return str_repeat("*", strlen($digits) - 4)
        . substr($digits, -4);
}


    /*
    |--------------------------------------------------------------------------
    | FIRST VISIT
    |--------------------------------------------------------------------------
    |
    | Send the OTPs generated by register.php.
    |
    | IMPORTANT:
    | Refreshing the page will NOT resend them because the raw OTPs
    | are removed from the session after the first send.
    |
    */
    if (
        $_SERVER["REQUEST_METHOD"] !== "POST" &&
        isset(
            $pending['email_otp'],
            $pending['phone_otp']
        )
) {
        $emailOtp = $pending['email_otp'];
        $phoneOtp = $pending['phone_otp'];
        

        $emailSent = sendEmailOTP(
            $email,
            $emailOtp
        );

        $smsSent = sendPhoneOTP(
            $phone,
            $phoneOtp
        );
       

        // Remove raw OTPs after sending.
        unset($pending['email_otp']);
        unset($pending['phone_otp']);

        if (!$emailSent || !$smsSent) {

            $generalError =
                "One or more verification codes could not be sent. "
                . "Please use the resend button.";

        } else {

            $success =
                "Verification codes have been sent.";
        }
    }


    /*
    |--------------------------------------------------------------------------
    | POST ACTION
    |--------------------------------------------------------------------------
    */

    if ($_SERVER["REQUEST_METHOD"] === "POST") {

        /*
        |--------------------------------------------------------------------------
        | CSRF CHECK
        |--------------------------------------------------------------------------
        */

        if (
            !isset($_POST['csrf_token']) ||
            !hash_equals(
                $_SESSION['csrf_token'],
                $_POST['csrf_token']
            )
        ) {

            $generalError =
                "Security validation failed. Please refresh the page.";

        } else {

            $action = $_POST['action'] ?? "";


            /*
            |--------------------------------------------------------------------------
            | VERIFY EMAIL
            |--------------------------------------------------------------------------
            */

            if ($action === "verify_email") {

                if (!empty($pending['email_verified'])) {

                    $success =
                        "Your email is already verified.";

                } else {

                    $emailOtp =
                        trim($_POST['email_otp'] ?? "");

                    if (!preg_match('/^\d{6}$/', $emailOtp)) {

                        $generalError =
                            "Please enter a valid 6-digit email OTP.";

                    } elseif (
                        empty($pending['email_otp_hash']) ||
                        empty($pending['email_otp_expires_at'])
                    ) {

                        $generalError =
                            "Email OTP is not available. Please resend the OTP.";

                    } elseif (
                        $pending['email_otp_expires_at'] < time()
                    ) {

                        $generalError =
                            "Email OTP has expired. Please resend the OTP.";

                    } elseif (
                        !password_verify(
                            $emailOtp,
                            $pending['email_otp_hash']
                        )
                    ) {

                        $generalError =
                            "Incorrect email OTP.";

                    } else {

                        $pending['email_verified'] = true;

                        $success =
                            "Email verified successfully.";

                    }
                }
            }


            /*
            |--------------------------------------------------------------------------
            | VERIFY PHONE
            |--------------------------------------------------------------------------
            */

            elseif ($action === "verify_phone") {

                if (!empty($pending['phone_verified'])) {

                    $success =
                        "Your mobile number is already verified.";

                } else {

                    $phoneOtp =
                        trim($_POST['phone_otp'] ?? "");

                    if (!preg_match('/^\d{6}$/', $phoneOtp)) {

                        $generalError =
                            "Please enter a valid 6-digit mobile OTP.";

                    } elseif (
                        empty($pending['phone_otp_hash']) ||
                        empty($pending['phone_otp_expires_at'])
                    ) {

                        $generalError =
                            "Mobile OTP is not available. Please resend the OTP.";

                    } elseif (
                        $pending['phone_otp_expires_at'] < time()
                    ) {

                        $generalError =
                            "Mobile OTP has expired. Please resend the OTP.";

                    } elseif (
                        !password_verify(
                            $phoneOtp,
                            $pending['phone_otp_hash']
                        )
                    ) {

                        $generalError =
                            "Incorrect mobile OTP.";

                    } else {

                        $pending['phone_verified'] = true;

                        $success =
                            "Mobile number verified successfully.";

                    }
                }
            }


            /*
            |--------------------------------------------------------------------------
            | RESEND EMAIL OTP
            |--------------------------------------------------------------------------
            */

            elseif ($action === "resend_email") {

                if (!empty($pending['email_verified'])) {

                    $generalError =
                        "Your email is already verified.";

                } else {

                    $emailOtp =
                        (string) random_int(100000, 999999);

                    $pending['email_otp_hash'] =
                        password_hash(
                            $emailOtp,
                            PASSWORD_DEFAULT
                        );

                    $pending['email_otp'] = $emailOtp;

                    $pending['email_otp_expires_at'] = time() + 600;

                    $emailSent =
                    sendEmailOTP(
                        $email,
                        $emailOtp
                    );

                    unset($pending['email_otp']);

                    if ($emailSent) {

                        $success =
                            "A new email OTP has been sent.";

                    } else {

    $generalError = "Unable to send email OTP: " .
                    ($GLOBALS['generalError'] ?? 'Unknown SMTP error');
}
                }
            }


            /*
            |--------------------------------------------------------------------------
            | RESEND PHONE OTP
            |--------------------------------------------------------------------------
            */

            elseif ($action === "resend_phone") {

                if (!empty($pending['phone_verified'])) {

                    $generalError =
                        "Your mobile number is already verified.";

                } else {

                    $phoneOtp =
                        (string) random_int(100000, 999999);

                    $pending['phone_otp_hash'] =
                        password_hash(
                            $phoneOtp,
                            PASSWORD_DEFAULT
                        );

                    $pending['phone_otp'] = $phoneOtp;

                    $pending['phone_otp_expires_at'] = time() + 600;

                    $smsSent =
                        sendPhoneOTP(
                            $phone,
                            $phoneOtp
                        );

                    unset($pending['phone_otp']);

                    if ($smsSent) {

                        $success =
                            "A new mobile OTP has been sent.";

                    } else {

                        $generalError =
                            "Unable to send mobile OTP.";
                    }
                }
            }


            /*
            |--------------------------------------------------------------------------
            | CHECK WHETHER BOTH ARE VERIFIED
            |--------------------------------------------------------------------------
            */

            if (
                empty($generalError) &&
                !empty($pending['email_verified']) &&
                !empty($pending['phone_verified'])
            ) {

                /*
                |--------------------------------------------------------------------------
                | IMPORTANT:
                | Re-check duplicate email/phone immediately before INSERT.
                |--------------------------------------------------------------------------
                */

                $check = $conn->prepare(
                    "SELECT id FROM {$table}
                     WHERE email = ? OR phone = ?
                     LIMIT 1"
                );

                $check->bind_param(
                    "ss",
                    $pending['email'],
                    $pending['phone']
                );

                $check->execute();

                $existing =
                    $check->get_result()->fetch_assoc();

                $check->close();


                if ($existing) {

                    unset($_SESSION['pending_verification']);

                    $generalError =
                        "An account with this email or mobile number already exists.";

                } else {

                    /*
                    |--------------------------------------------------------------------------
                    | INSERT PATIENT
                    |--------------------------------------------------------------------------
                    */

                    if ($userType === "patient") {

                        $stmt = $conn->prepare(
                            "INSERT INTO patients
                            (
                                first_name,
                                last_name,
                                email,
                                phone,
                                dob,
                                gender,
                                blood_group,
                                password,
                                email_verified,
                                phone_verified
                            )
                            VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, 1)"
                        );

                        if (!$stmt) {

                            $generalError =
                                "Unable to prepare patient account.";

                        } else {

                            $stmt->bind_param(
                                "ssssssss",
                                $pending['first_name'],
                                $pending['last_name'],
                                $pending['email'],
                                $pending['phone'],
                                $pending['dob'],
                                $pending['gender'],
                                $pending['blood_group'],
                                $pending['password_hash']
                            );
                        }

                    } else {

                        /*
                        |--------------------------------------------------------------------------
                        | Read temporary verification photo
                        |--------------------------------------------------------------------------
                        */

                        $tempPhotoFilename =
                            $pending['verification_photo_temp'] ?? '';

                        $photoType =
                            $pending['verification_photo_type'] ?? '';

                        $tempPhotoPath =
                            __DIR__
                            . '/storage/temp_verification/'
                            . basename($tempPhotoFilename);

                        if (
                            empty($tempPhotoFilename) ||
                            !is_file($tempPhotoPath)
                        ) {

                            $generalError =
                                "Doctor verification document is missing. "
                                . "Please restart the registration process.";

                        } elseif (
                            !in_array(
                                $photoType,
                                ['image/jpeg', 'image/png', 'image/webp'],
                                true
                            )
                        ) {

                            $generalError =
                                "Invalid verification document type.";

                        } else {

                            $photoData =
                                file_get_contents($tempPhotoPath);

                            if ($photoData === false) {

                                $generalError =
                                    "Unable to read the verification document.";

                            } else {

                                $stmt = $conn->prepare(
                                    "INSERT INTO doctors
                                    (
                                        first_name,
                                        last_name,
                                        email,
                                        phone,
                                        dob,
                                        gender,
                                        blood_group,
                                        password,
                                        license_number,
                                        specialty,
                                        verification_photo,
                                        verification_photo_type,
                                        email_verified,
                                        phone_verified,
                                        verification_status,
                                        is_verified
                                    )
                                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 1, 'pending', 0)"
                                );
                                 
                                if (!$stmt) {

                                        error_log(
                                            "DOCTOR INSERT PREPARE ERROR: " . $conn->error
                                        );

                                        $generalError =
                                            "Unable to prepare doctor account: " . $conn->error;
                                    } else {

                                    $null = null;

                                    $stmt->bind_param(
                                        "ssssssssssbs",
                                        $pending['first_name'],
                                        $pending['last_name'],
                                        $pending['email'],
                                        $pending['phone'],
                                        $pending['dob'],
                                        $pending['gender'],
                                        $pending['blood_group'],
                                        $pending['password_hash'],
                                        $pending['license_number'],
                                        $pending['specialization'],
                                        $null,
                                        $photoType
                                    );

                                    $stmt->send_long_data(
                                        10,
                                        $photoData
                                    );
                                }
                            }
                        }
                    }
                   

                    /*
                    |--------------------------------------------------------------------------
                    | INSERT USER
                    |--------------------------------------------------------------------------
                    */
                    if (
                        empty($generalError) &&
                        isset($stmt) &&
                        $stmt instanceof mysqli_stmt
                    ) {

                        if ($stmt->execute()) {

                            $stmt->close();

                            // Delete temporary doctor verification photo
                            if (
                                $userType === 'doctor' &&
                                !empty($tempPhotoPath) &&
                                is_file($tempPhotoPath)
                            ) {
                                @unlink($tempPhotoPath);
                            }

                            unset($_SESSION['pending_verification']);

                            $_SESSION['csrf_token'] =
                                bin2hex(random_bytes(32));

                            $success =
                                "Your account has been verified successfully! "
                                . "Redirecting to login...";

                            echo "
                                <script>
                                    setTimeout(function() {
                                        window.location.href = 'login.php';
                                    }, 1800);
                                </script>
                            ";

                        } else {

                            $generalError =
                                "Unable to create your account. Please try again.";

                            $stmt->close();
                        }
                    }
                    
                    
                    
                }
            }
        }
    }

?>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >

    <title>Human Care - Verify Account</title>

    <link
        rel="stylesheet"
        href="styles/verify.css"
    >

</head>

<body>

<div class="verify-card">

    <h2>Verify Your Account</h2>

    <p class="verify-subtitle">
        Verify your email address and mobile number separately.
    </p>


    <?php if ($generalError): ?>

        <div class="general-error">
            <?php echo htmlspecialchars($generalError); ?>
        </div>

    <?php endif; ?>


    <?php if ($success): ?>

        <div class="success-message">
            <?php echo htmlspecialchars($success); ?>
        </div>

    <?php endif; ?>


    <!-- EMAIL VERIFICATION -->

    <div class="verify-item">

        <strong>📧 Email Address</strong>

        <span>
            <?php echo htmlspecialchars(maskEmail($email)); ?>
        </span>

        <?php if (!empty($pending['email_verified'])): ?>

            <p class="verified">
                ✓ Email Verified
            </p>

        <?php else: ?>

            <form method="POST" autocomplete="off">

                <input
                    type="hidden"
                    name="csrf_token"
                    value="<?php echo htmlspecialchars($_SESSION['csrf_token']); ?>"
                >

                <input
                    type="hidden"
                    name="action"
                    value="verify_email"
                >

                <input
                    class="verify-input"
                    type="text"
                    name="email_otp"
                    inputmode="numeric"
                    pattern="\d{6}"
                    maxlength="6"
                    placeholder="000000"
                    required
                >

                <button
                    type="submit"
                    class="verify-btn"
                >
                    Verify Email
                </button>

            </form>


            <form method="POST">

                <input
                    type="hidden"
                    name="csrf_token"
                    value="<?php echo htmlspecialchars($_SESSION['csrf_token']); ?>"
                >

                <input
                    type="hidden"
                    name="action"
                    value="resend_email"
                >

                <button
                    type="submit"
                    class="resend-btn"
                >
                    Resend Email OTP
                </button>

            </form>

        <?php endif; ?>

    </div>


    <!-- MOBILE VERIFICATION -->

    <div class="verify-item">

        <strong>📱 Mobile Number</strong>

        <span>
            <?php echo htmlspecialchars(maskPhone($phone)); ?>
        </span>

        <?php if (!empty($pending['phone_verified'])): ?>

            <p class="verified">
                ✓ Mobile Number Verified
            </p>

        <?php else: ?>

            <form method="POST" autocomplete="off">

                <input
                    type="hidden"
                    name="csrf_token"
                    value="<?php echo htmlspecialchars($_SESSION['csrf_token']); ?>"
                >

                <input
                    type="hidden"
                    name="action"
                    value="verify_phone"
                >

                <input
                    class="verify-input"
                    type="text"
                    name="phone_otp"
                    inputmode="numeric"
                    pattern="\d{6}"
                    maxlength="6"
                    placeholder="000000"
                    required
                >

                <button
                    type="submit"
                    class="verify-btn"
                >
                    Verify Mobile
                </button>

            </form>


            <form method="POST">

                <input
                    type="hidden"
                    name="csrf_token"
                    value="<?php echo htmlspecialchars($_SESSION['csrf_token']); ?>"
                >

                <input
                    type="hidden"
                    name="action"
                    value="resend_phone"
                >

                <button
                    type="submit"
                    class="resend-btn"
                >
                    Resend Mobile OTP
                </button>

            </form>

        <?php endif; ?>

    </div>


    <p style="text-align:center; margin-top:20px;">

        <a href="register.php">
            ← Back to Registration
        </a>

    </p>

</div>

</body>

</html>